### ISSUE TITLE
Korean output does not work.

### ISSUE THREAD

**Issue by BKLFIRST** [w-okada/ttsclient#6]
When I type in Korean and click run, the following message appears in the console and it doesn't work.

you have to install python-mecab-ko. install it...
python version: 3.10.9 (main, Mar  1 2023, 12:22:43) [Clang 14.0.6 ]
MEIPASS: /var/folders/m0/s_n5jkvn6nlbfns4fsq_qb0r0000gn/T/_MEI72qYaa
Failed to load python-mecab-ko: No module named 'mecab'
---- generate voice(elapsed:42423.6ms) ----

If you look at the log file, you will see the following log error.
2024-09-17 00:39:39,347 - ttsclient  - validation_error_log - ERROR - Exception: 'NoneType' object has no attribute 'pos' - ttsclient/server/validation_error_logging_route.py - 27
2024-09-17 00:39:39,347 - ttsclient  - validation_error_log - ERROR - Exception tb: Traceback (most recent call last):
  File "ttsclient/server/validation_error_logging_route.py", line 16, in custom_route_handler
  File "fastapi/routing.py", line 278, in app
  File "fastapi/routing.py", line 193, in run_endpoint_function
  File "starlette/concurrency.py", line 42, in run_in_threadpool
  File "anyio/to_thread.py", line 56, in run_sync
  File "anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
  File "anyio/_backends/_asyncio.py", line 859, in run
  File "ttsclient/server/tts_server_rest_api_tts_manager.py", line 22, in post_generate_voice
  File "ttsclient/tts/tts_manager/tts_manager.py", line 51, in run
  File "ttsclient/tts/tts_manager/pipeline/gpt_sovits_pipeline.py", line 198, in run
  File "ttsclient/tts/tts_manager/phone_extractor/bert_phone_extractor.py", line 136, in get_phones_and_bert
  File "ttsclient/tts/tts_manager/phone_extractor/bert_phone_extractor.py", line 55, in _clean_text_inf
  File "ttsclient/tts/tts_manager/text/cleaner.py", line 55, in clean_text
  File "ttsclient/tts/tts_manager/text/korean.py", line 222, in g2p
  File "g2pk2/g2pk2.py", line 157, in __call__
  File "g2pk2/utils.py", line 166, in annotate
AttributeError: 'NoneType' object has no attribute 'pos'
 - ttsclient/server/validation_error_logging_route.py - 28
 
 Korean output does not work on Windows 10 and does not work smoothly on Mac 14.6.1.

**Comment by BKLFIRST** [comment]
pip install mecab 

The command has already been run and the installation has been completed.

**Comment by w-okada** [comment]
Please clone and use the repository.
